# theme.toml template for a Hugo theme
# See https://github.com/CharbelTabet/hugo-dark-orchid for an example

name = "Dark Orchid"
license = "MIT"
licenselink = "https://github.com/CharbelTabet/hugo-dark-orchid/master/LICENSE.md"
description = "Hugo Dark Orchid is a personal webiste theme made for content creators, designers and coders to showcase their work and expertise"
homepage = "https://github.com/CharbelTabet/hugo-dark-orchid"
tags = ["minimal","responsive","clean","modern","colors","portfolio","blog","skills","experience","services","uicardio"]
features = ["blog","services","portfolio","contact","skills","formspree","responsive"]
min_version = "0.31.1"

[author]
  name = "Charbel Tabet"
  homepage = "https://www.charbeltabet.com"

[developer]
	name = "Charbel Tabet"
	homepage = "https://www.ap0lo.com"